insert into Tags (TagId, Tag) values (1, 'lectus');
insert into Tags (TagId, Tag) values (2, 'nisl');
insert into Tags (TagId, Tag) values (3, 'pretium nisl');
insert into Tags (TagId, Tag) values (4, 'ipsum');
insert into Tags (TagId, Tag) values (5, 'curae');
insert into Tags (TagId, Tag) values (6, 'convallis duis');
insert into Tags (TagId, Tag) values (7, 'metus aenean');
insert into Tags (TagId, Tag) values (8, 'ipsum praesent');
insert into Tags (TagId, Tag) values (9, 'bibendum imperdiet');
insert into Tags (TagId, Tag) values (10, 'dis parturient');
insert into Tags (TagId, Tag) values (11, 'vel ipsum');
insert into Tags (TagId, Tag) values (12, 'nec nisi');
insert into Tags (TagId, Tag) values (13, 'id lobortis');
insert into Tags (TagId, Tag) values (14, 'sapien in');
insert into Tags (TagId, Tag) values (15, 'in faucibus orci');
insert into Tags (TagId, Tag) values (16, 'sit amet');
insert into Tags (TagId, Tag) values (17, 'amet');
insert into Tags (TagId, Tag) values (18, 'elementum in');
insert into Tags (TagId, Tag) values (19, 'porttitor');
insert into Tags (TagId, Tag) values (20, 'proin');
insert into Tags (TagId, Tag) values (21, 'ipsum integer a');
insert into Tags (TagId, Tag) values (22, 'congue');
insert into Tags (TagId, Tag) values (23, 'ipsum integer a');
insert into Tags (TagId, Tag) values (24, 'diam nam');
insert into Tags (TagId, Tag) values (25, 'pellentesque ultrices');
insert into Tags (TagId, Tag) values (26, 'vel lectus in');
insert into Tags (TagId, Tag) values (27, 'eget nunc');
insert into Tags (TagId, Tag) values (28, 'orci');
insert into Tags (TagId, Tag) values (29, 'in lacus curabitur');
insert into Tags (TagId, Tag) values (30, 'ligula in lacus');
insert into Tags (TagId, Tag) values (31, 'cubilia');
insert into Tags (TagId, Tag) values (32, 'pulvinar nulla');
insert into Tags (TagId, Tag) values (33, 'mauris vulputate elementum');
insert into Tags (TagId, Tag) values (34, 'sapien');
insert into Tags (TagId, Tag) values (35, 'nibh in hac');
insert into Tags (TagId, Tag) values (36, 'nonummy integer non');
insert into Tags (TagId, Tag) values (37, 'rutrum');
insert into Tags (TagId, Tag) values (38, 'enim leo rhoncus');
insert into Tags (TagId, Tag) values (39, 'felis eu sapien');
insert into Tags (TagId, Tag) values (40, 'ornare imperdiet sapien');
insert into Tags (TagId, Tag) values (41, 'turpis a pede');
insert into Tags (TagId, Tag) values (42, 'integer');
insert into Tags (TagId, Tag) values (43, 'vel lectus in');
insert into Tags (TagId, Tag) values (44, 'tincidunt eu felis');
insert into Tags (TagId, Tag) values (45, 'vulputate vitae nisl');
insert into Tags (TagId, Tag) values (46, 'tristique');
insert into Tags (TagId, Tag) values (47, 'at diam nam');
insert into Tags (TagId, Tag) values (48, 'in hac');
insert into Tags (TagId, Tag) values (49, 'aliquam');
insert into Tags (TagId, Tag) values (50, 'amet');
insert into Tags (TagId, Tag) values (51, 'augue quam');
insert into Tags (TagId, Tag) values (52, 'sit amet');
insert into Tags (TagId, Tag) values (53, 'orci');
insert into Tags (TagId, Tag) values (54, 'tristique');
insert into Tags (TagId, Tag) values (55, 'sapien iaculis');
insert into Tags (TagId, Tag) values (56, 'ante ipsum');
insert into Tags (TagId, Tag) values (57, 'iaculis');
insert into Tags (TagId, Tag) values (58, 'at ipsum ac');
insert into Tags (TagId, Tag) values (59, 'est');
insert into Tags (TagId, Tag) values (60, 'metus vitae ipsum');
insert into Tags (TagId, Tag) values (61, 'placerat ante');
insert into Tags (TagId, Tag) values (62, 'vestibulum proin eu');
insert into Tags (TagId, Tag) values (63, 'curabitur at ipsum');
insert into Tags (TagId, Tag) values (64, 'luctus nec molestie');
insert into Tags (TagId, Tag) values (65, 'morbi sem');
insert into Tags (TagId, Tag) values (66, 'lacinia nisi venenatis');
insert into Tags (TagId, Tag) values (67, 'molestie hendrerit');
insert into Tags (TagId, Tag) values (68, 'sit amet');
insert into Tags (TagId, Tag) values (69, 'tempor convallis');
insert into Tags (TagId, Tag) values (70, 'nulla neque');
insert into Tags (TagId, Tag) values (71, 'enim leo rhoncus');
insert into Tags (TagId, Tag) values (72, 'a');
insert into Tags (TagId, Tag) values (73, 'consequat morbi');
insert into Tags (TagId, Tag) values (74, 'neque');
insert into Tags (TagId, Tag) values (75, 'rutrum neque');
insert into Tags (TagId, Tag) values (76, 'justo morbi');
insert into Tags (TagId, Tag) values (77, 'dui');
insert into Tags (TagId, Tag) values (78, 'congue elementum in');
insert into Tags (TagId, Tag) values (79, 'scelerisque quam');
insert into Tags (TagId, Tag) values (80, 'consequat');
insert into Tags (TagId, Tag) values (81, 'potenti');
insert into Tags (TagId, Tag) values (82, 'accumsan');
insert into Tags (TagId, Tag) values (83, 'posuere nonummy');
insert into Tags (TagId, Tag) values (84, 'consequat metus');
insert into Tags (TagId, Tag) values (85, 'velit nec nisi');
insert into Tags (TagId, Tag) values (86, 'nunc');
insert into Tags (TagId, Tag) values (87, 'tellus nulla ut');
insert into Tags (TagId, Tag) values (88, 'pede justo');
insert into Tags (TagId, Tag) values (89, 'quis justo');
insert into Tags (TagId, Tag) values (90, 'justo etiam');
insert into Tags (TagId, Tag) values (91, 'ante ipsum primis');
insert into Tags (TagId, Tag) values (92, 'neque aenean');
insert into Tags (TagId, Tag) values (93, 'cursus');
insert into Tags (TagId, Tag) values (94, 'orci');
insert into Tags (TagId, Tag) values (95, 'sagittis');
insert into Tags (TagId, Tag) values (96, 'euismod scelerisque');
insert into Tags (TagId, Tag) values (97, 'sit amet');
insert into Tags (TagId, Tag) values (98, 'gravida sem praesent');
insert into Tags (TagId, Tag) values (99, 'a');
insert into Tags (TagId, Tag) values (100, 'velit eu');
