insert into Tags (TagId, Tag) values (1, 'lobortis ligula');
insert into Tags (TagId, Tag) values (2, 'a pede');
insert into Tags (TagId, Tag) values (3, 'proin');
insert into Tags (TagId, Tag) values (4, 'amet consectetuer');
insert into Tags (TagId, Tag) values (5, 'sed');
insert into Tags (TagId, Tag) values (6, 'habitasse');
insert into Tags (TagId, Tag) values (7, 'sapien urna');
insert into Tags (TagId, Tag) values (8, 'orci mauris');
insert into Tags (TagId, Tag) values (9, 'augue vel');
insert into Tags (TagId, Tag) values (10, 'risus praesent');
insert into Tags (TagId, Tag) values (11, 'amet eros');
insert into Tags (TagId, Tag) values (12, 'rhoncus aliquet');
insert into Tags (TagId, Tag) values (13, 'ridiculus');
insert into Tags (TagId, Tag) values (14, 'hac habitasse');
insert into Tags (TagId, Tag) values (15, 'consequat varius');
insert into Tags (TagId, Tag) values (16, 'ultrices posuere');
insert into Tags (TagId, Tag) values (17, 'blandit mi');
insert into Tags (TagId, Tag) values (18, 'vulputate');
insert into Tags (TagId, Tag) values (19, 'tortor id');
insert into Tags (TagId, Tag) values (20, 'molestie');
insert into Tags (TagId, Tag) values (21, 'congue risus');
insert into Tags (TagId, Tag) values (22, 'eget');
insert into Tags (TagId, Tag) values (23, 'quis tortor');
insert into Tags (TagId, Tag) values (24, 'in felis');
insert into Tags (TagId, Tag) values (25, 'integer');
insert into Tags (TagId, Tag) values (26, 'ultrices aliquet');
insert into Tags (TagId, Tag) values (27, 'augue vestibulum');
insert into Tags (TagId, Tag) values (28, 'habitasse');
insert into Tags (TagId, Tag) values (29, 'magna');
insert into Tags (TagId, Tag) values (30, 'primis in');
insert into Tags (TagId, Tag) values (31, 'gravida');
insert into Tags (TagId, Tag) values (32, 'amet cursus');
insert into Tags (TagId, Tag) values (33, 'massa');
insert into Tags (TagId, Tag) values (34, 'nam dui');
insert into Tags (TagId, Tag) values (35, 'justo maecenas');
insert into Tags (TagId, Tag) values (36, 'cras');
insert into Tags (TagId, Tag) values (37, 'venenatis');
insert into Tags (TagId, Tag) values (38, 'sed');
insert into Tags (TagId, Tag) values (39, 'vivamus');
insert into Tags (TagId, Tag) values (40, 'ultrices');
insert into Tags (TagId, Tag) values (41, 'enim in');
insert into Tags (TagId, Tag) values (42, 'pellentesque');
insert into Tags (TagId, Tag) values (43, 'morbi vel');
insert into Tags (TagId, Tag) values (44, 'odio elementum');
insert into Tags (TagId, Tag) values (45, 'dui');
insert into Tags (TagId, Tag) values (46, 'amet');
insert into Tags (TagId, Tag) values (47, 'sem mauris');
insert into Tags (TagId, Tag) values (48, 'justo in');
insert into Tags (TagId, Tag) values (49, 'ante');
insert into Tags (TagId, Tag) values (50, 'rhoncus');
insert into Tags (TagId, Tag) values (51, 'libero');
insert into Tags (TagId, Tag) values (52, 'placerat');
insert into Tags (TagId, Tag) values (53, 'platea dictumst');
insert into Tags (TagId, Tag) values (54, 'ut nulla');
insert into Tags (TagId, Tag) values (55, 'nisi volutpat');
insert into Tags (TagId, Tag) values (56, 'nisl nunc');
insert into Tags (TagId, Tag) values (57, 'sed magna');
insert into Tags (TagId, Tag) values (58, 'at lorem');
insert into Tags (TagId, Tag) values (59, 'platea');
insert into Tags (TagId, Tag) values (60, 'fusce');
insert into Tags (TagId, Tag) values (61, 'turpis');
insert into Tags (TagId, Tag) values (62, 'euismod');
insert into Tags (TagId, Tag) values (63, 'vel nulla');
insert into Tags (TagId, Tag) values (64, 'eget congue');
insert into Tags (TagId, Tag) values (65, 'in');
insert into Tags (TagId, Tag) values (66, 'nunc');
insert into Tags (TagId, Tag) values (67, 'quam suspendisse');
insert into Tags (TagId, Tag) values (68, 'sapien');
insert into Tags (TagId, Tag) values (69, 'porttitor lacus');
insert into Tags (TagId, Tag) values (70, 'natoque');
insert into Tags (TagId, Tag) values (71, 'augue');
insert into Tags (TagId, Tag) values (72, 'praesent');
insert into Tags (TagId, Tag) values (73, 'nullam porttitor');
insert into Tags (TagId, Tag) values (74, 'primis in');
insert into Tags (TagId, Tag) values (75, 'vel augue');
insert into Tags (TagId, Tag) values (76, 'libero nullam');
insert into Tags (TagId, Tag) values (77, 'donec');
insert into Tags (TagId, Tag) values (78, 'aliquam augue');
insert into Tags (TagId, Tag) values (79, 'sit');
insert into Tags (TagId, Tag) values (80, 'nulla');
insert into Tags (TagId, Tag) values (81, 'in');
insert into Tags (TagId, Tag) values (82, 'dapibus at');
insert into Tags (TagId, Tag) values (83, 'lectus pellentesque');
insert into Tags (TagId, Tag) values (84, 'sit');
insert into Tags (TagId, Tag) values (85, 'nec');
insert into Tags (TagId, Tag) values (86, 'justo');
insert into Tags (TagId, Tag) values (87, 'id');
insert into Tags (TagId, Tag) values (88, 'gravida');
insert into Tags (TagId, Tag) values (89, 'eleifend');
insert into Tags (TagId, Tag) values (90, 'sit amet');
insert into Tags (TagId, Tag) values (91, 'consequat ut');
insert into Tags (TagId, Tag) values (92, 'nisi venenatis');
insert into Tags (TagId, Tag) values (93, 'nunc');
insert into Tags (TagId, Tag) values (94, 'faucibus');
insert into Tags (TagId, Tag) values (95, 'neque');
insert into Tags (TagId, Tag) values (96, 'vestibulum');
insert into Tags (TagId, Tag) values (97, 'in');
insert into Tags (TagId, Tag) values (98, 'et ultrices');
insert into Tags (TagId, Tag) values (99, 'ac nulla');
insert into Tags (TagId, Tag) values (100, 'eget elit');
